using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using RobloxFiles;
using Rbx2Source.Assembler;
using Rbx2Source.Geometry;

namespace Rbx2Source.StudioMdl
{
    /// <summary>
    /// Writer Implementation for Source's Studiomdl Data format.
    /// See: https://developer.valvesoftware.com/wiki/Studiomdl_Data
    /// </summary>

    public class StudioMdlWriter : IDisposable
    {
        private StringWriter buffer;

        private Dictionary<string, int> nodeIndexByName;
        private Dictionary<Node, int> nodeIndexByRef;
        private Dictionary<Node, int> nodeParentIndex;
        private Dictionary<Mesh, string[]> vertexCoordCache;

        public List<Node> Nodes;
        public List<Triangle> Triangles;
        public List<BoneKeyframe> Skeleton;
        public Dictionary<string, ValveMaterial> Materials;

        internal void EnsureNodeIndexCache()
        {
            if (nodeIndexByRef != null)
                return;

            int count = Nodes.Count;
            var byName = new Dictionary<string, int>(count);
            var byRef = new Dictionary<Node, int>(count);
            var parents = new Dictionary<Node, int>(count);

            for (int i = 0; i < count; i++)
            {
                Node node = Nodes[i];
                byRef[node] = i;

                string name = node.Name;
                if (name != null && !byName.ContainsKey(name))
                    byName[name] = i;
            }

            for (int i = 0; i < count; i++)
                parents[Nodes[i]] = ComputeParentIndex(Nodes[i], count);

            nodeIndexByName = byName;
            nodeIndexByRef = byRef;
            nodeParentIndex = parents;
        }

        private int ComputeParentIndex(Node node, int count)
        {
            BasePart part0 = node.StudioBone.Part0;
            BasePart part1 = node.StudioBone.Part1;

            if (part0 != part1)
            {
                StudioBone bone = node.StudioBone;

                for (int i = 0; i < count; i++)
                {
                    Node n = Nodes[i];
                    StudioBone b = n.StudioBone;

                    if (b != bone && b.Part1 == part0)
                        return i;
                }
            }

            return -1;
        }

        internal int GetNodeIndexByName(string name)
        {
            var cache = nodeIndexByName;

            if (cache != null && name != null && cache.TryGetValue(name, out int nodeIndex))
                return nodeIndex;

            return -1;
        }

        internal int GetNodeIndex(Node node)
        {
            var cache = nodeIndexByRef;

            if (cache != null && cache.TryGetValue(node, out int nodeIndex))
                return nodeIndex;

            return -1;
        }

        internal int GetParentIndex(Node node)
        {
            var cache = nodeParentIndex;

            if (cache != null && cache.TryGetValue(node, out int parentIndex))
                return parentIndex;

            return -1;
        }

        internal string[] GetCachedVertexCoords(Mesh mesh)
        {
            var cache = vertexCoordCache;

            if (cache != null && cache.TryGetValue(mesh, out string[] coords))
                return coords;

            return null;
        }

        internal void SetCachedVertexCoords(Mesh mesh, string[] coords)
        {
            var cache = vertexCoordCache;

            if (cache == null)
            {
                cache = new Dictionary<Mesh, string[]>();
                vertexCoordCache = cache;
            }

            cache[mesh] = coords;
        }

        private void WriteEntities<T>(List<T> entities) where T : IStudioMdlEntity<T>
        {
            if (entities.Count > 0)
            {
                var groupName = entities[0].GroupName;
                buffer.WriteLine('\n' + groupName);

                foreach (T entity in entities)
                    entity.WriteStudioMdl(buffer, this, entities);

                buffer.WriteLine("end");
            }
        }

        public string BuildFile(bool writeGeometry = true)
        {
            buffer = new StringWriter();

            buffer.WriteLine("// Generated by MaximumADHD's Rbx2Source tool!");
            buffer.WriteLine("// Please do not edit this file while the program is running.");
            buffer.WriteLine("// The file was set to read-only for a reason ;)\n");
            buffer.WriteLine("version 1");

            WriteEntities(Nodes);

            nodeIndexByName = null;
            nodeIndexByRef = null;
            nodeParentIndex = null;
            EnsureNodeIndexCache();

            WriteEntities(Skeleton);

            if (writeGeometry)
                WriteEntities(Triangles);

            return buffer.ToString();
        }

        public StudioMdlWriter()
        {
            Nodes     = new List<Node>();
            Triangles = new List<Triangle>();
            Skeleton  = new List<BoneKeyframe>();
            Materials = new Dictionary<string, ValveMaterial>();
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            buffer.Dispose();
        }
    }
}
